name: Cypress
on: [push]
jobs:
  components:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress component tests
        uses: cypress-io/github-action@v4
        with:
          component: true